# Generated by Django 5.0.6 on 2024-07-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bk_au_temp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='here is the lan'),
            preserve_default=False,
        ),
    ]
