# Generated by Django 5.0.6 on 2024-07-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0005_pie_bak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pie',
            name='bak',
        ),
    ]
