# Generated by Django 5.0.6 on 2024-07-26 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_remove_pie_bak'),
    ]

    operations = [
        migrations.AddField(
            model_name='pie',
            name='backery',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='bk', to='test.user'),
            preserve_default=False,
        ),
    ]
