# Generated by Django 5.0.6 on 2024-07-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0007_pie_backery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pie',
            name='backery',
        ),
    ]
