# Generated by Django 5.0.6 on 2024-07-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi', '0002_tv_show_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv_show',
            name='title',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
