# Generated by Django 5.0.6 on 2024-07-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi', '0003_alter_tv_show_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv_show',
            name='title',
            field=models.CharField(max_length=45),
        ),
    ]
